title: BubblesTech
subtitle: A Madman Team of Engineers
description: >- # this means to ignore newlines until "baseurl:"
  BubblesTech is a fast, lightweight and fully equipped product development team that is optimized for speed and reliability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
      #    - text: Shop
      #url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: Logo.png
author: BubblesTech
author_bio: Sometimes you should call the army...But sometimes, you gotta call Rambo...
author_email: "info@bubblestech.com"
author_location: USA
author_website_url: "https://bubblestech.com"
typewrite-text: We help you get your product design off the paper and into the factory!

# Experiences
author_clients:
            - company_name: Silver Linings
              company_logo: projects/silverlinings.png
              designation: Hardware and Firmware Lead
              visibility: true

            - company_name: Wagz
              company_logo: projects/wagz.png
              company_url: https://wagz.com
              designation: Lead Hardware/Firmware Engineer/Director of Hardware & Firmware
              visibility: true

            - company_name: Shark Ninja
              company_logo: projects/sharkninja.png
              company_url: https://sharkninja.com
              designation: Hardware Engineering Subcontractor
              visibility: true

            - company_name: Jabra GN
              company_logo: projects/jabra.png
              company_url: https://jabra.com
              designation: Hardware and Firmware Engineer
              visibility: true

            - company_name: VXi BlueParrott
              company_logo: projects/vxi.png
              company_url: https://blueparrott.com
              designation: Hardware and Firmware Engineer
              visibility: true

            - company_name: General Electric Power Division
              company_logo: projects/ge.png
              company_url: https://generalelectric.com
              designation: Hardware Validation Engineer
              visibility: true

# Education
author_education_details:
              - college_logo: umaine.png
                college_name: UMaine
                college_url: https://ece.umaine.edu
                college_degree: Mathematics, Computer & Electrical Engineering
                description: Bachelors of Science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: projects/hydra.png
                project_title: Hydra Personal Watercraft Controller
                project_description: A 3500W capable Electric Water Propulsion Solution for Personal Watercraft
                #project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: projects/Lights.png
                project_title: Ill-Luminator Lights
                project_description: A 600W Platform for Automating Contained Horniculture Grow Applications
                #project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: mc_gdb
github_username:  mcgdb
linkedin_username: dale-goodman-7649274

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
#getform_endpoint:
formspree_endpoint: xgerlbga
formspree_email: info@bubblestech.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
